# Base configuration for benchmarks
spring:
  application:
    name: error-monitor-benchmark
  
  main:
    web-application-type: servlet
    
server:
  port: 8080
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  
  metrics:
    export:
      simple:
        enabled: true
        
logging:
  level:
    com.nnegi88.errormonitor: INFO
    org.springframework.web: WARN