name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Spring Boot Error Monitor Starter are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: input
    id: spring-boot-version
    attributes:
      label: Spring Boot Version
      description: What version of Spring Boot are you using?
      placeholder: e.g., 3.2.0
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Java Version
      description: What version of Java are you using?
      placeholder: e.g., 17, 21
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Please share your error monitor configuration (application.yml/properties)
      render: yaml
      placeholder: |
        spring:
          error-monitor:
            enabled: true
            notification:
              platform: "slack"
              slack:
                webhook-url: "***"

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true