blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/nnegi88/spring-boot-error-monitor-starter/security/advisories/new
    about: Please report security vulnerabilities through GitHub Security Advisories