# Basic profile - Error monitoring enabled with minimal features
spring:
  error-monitor:
    enabled: true
    
    notification:
      platform: "slack"
      slack:
        webhook-url: "http://localhost:9999/mock-webhook"
        
    rate-limiting:
      max-errors-per-minute: 100
      burst-limit: 10
      
    filtering:
      minimum-severity: "ERROR"
      
    metrics:
      enabled: false
      
    analytics:
      enabled: false