# Full profile - All features enabled
spring:
  error-monitor:
    enabled: true
    
    notification:
      platform: "both"
      slack:
        webhook-url: "http://localhost:9999/mock-slack-webhook"
        channel: "#benchmark-alerts"
        username: "Benchmark Monitor"
        icon-emoji: ":chart_with_upwards_trend:"
        
      teams:
        webhook-url: "http://localhost:9999/mock-teams-webhook"
        title: "Benchmark Error Alert"
        theme-color: "FF0000"
        
    rate-limiting:
      max-errors-per-minute: 1000
      burst-limit: 100
      
    filtering:
      enabled-packages:
        - "com.nnegi88.errormonitor.benchmark"
      excluded-exceptions:
        - "java.lang.IllegalStateException"
      minimum-severity: "WARN"
      
    context:
      include-request-details: true
      include-stack-trace: true
      max-stack-trace-lines: 50
      mask-sensitive-data: true
      
    metrics:
      enabled: true
      tags:
        - "service:benchmark"
        - "environment:test"
        - "version:1.0.0"
      
    analytics:
      enabled: true
      retention-period: "24h"
      aggregation-enabled: true
      trend-analysis-enabled: true