name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  validate-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Validate version format
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        BRANCH_NAME="${{ github.ref_name }}"
        
        echo "Current version: $VERSION"
        echo "Current branch: $BRANCH_NAME"
        
        if [[ "$BRANCH_NAME" == "main" ]] && [[ $VERSION == *"-SNAPSHOT" ]]; then
          echo "❌ ERROR: Main branch should only contain release versions!"
          exit 1
        fi
        
        if [[ "$BRANCH_NAME" == "develop" ]] && [[ $VERSION != *"-SNAPSHOT" ]]; then
          echo "❌ ERROR: Develop branch should only contain SNAPSHOT versions!"
          exit 1
        fi

  test:
    needs: validate-version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11, 17]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run tests
      run: mvn clean test -B -Dgpg.skip=true

    - name: Run integration tests
      run: mvn verify -B -Dgpg.skip=true

    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests (Java ${{ matrix.java-version }})
        path: target/surefire-reports/*.xml
        reporter: java-junit

    - name: Upload coverage to Codecov
      if: matrix.java-version == '11'
      uses: codecov/codecov-action@v3
      with:
        file: target/site/jacoco/jacoco.xml
        fail_ci_if_error: false

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn clean compile -B -Dgpg.skip=true

    - name: Package
      run: mvn package -DskipTests -B -Dgpg.skip=true

    - name: Verify JAR structure
      run: |
        jar -tf target/*.jar | head -20
        ls -la target/

