name: Publish to GitHub Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Publish to GitHub Packages
      run: |
        mvn deploy -DskipTests -Dgpg.skip=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}