name: Version Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  validate-version:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Validate version format
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        BRANCH_NAME="${{ github.ref_name }}"
        
        echo "Current version: $VERSION"
        echo "Current branch: $BRANCH_NAME"
        
        # For main branch - must be a release version
        if [[ "$BRANCH_NAME" == "main" ]]; then
          if [[ $VERSION == *"-SNAPSHOT" ]]; then
            echo "❌ ERROR: Main branch should only contain release versions!"
            echo "Found SNAPSHOT version: $VERSION"
            echo "Please remove -SNAPSHOT from the version before pushing to main"
            exit 1
          else
            echo "✅ Version is valid for main branch: $VERSION"
          fi
        fi
        
        # For develop branch - must be a SNAPSHOT version
        if [[ "$BRANCH_NAME" == "develop" ]]; then
          if [[ $VERSION != *"-SNAPSHOT" ]]; then
            echo "❌ ERROR: Develop branch should only contain SNAPSHOT versions!"
            echo "Found release version: $VERSION"
            echo "Please add -SNAPSHOT to the version before pushing to develop"
            exit 1
          else
            echo "✅ Version is valid for develop branch: $VERSION"
          fi
        fi